### ISSUE TITLE
Sketch of ideas for a CRM

### ISSUE THREAD

**Issue by c-t-k** [PhillyDSA/phillydsa-crm#1]
# Motivation

Right now we have a somewhat spotty way of tracking membership information. That membership information is stored in Action Network whenever we get a new member roll from DSA national and is imported via CSV. There are several problems w/ this process:

* Importing via CSV overwrites previously set fields, so if someone has changed, for example, their address at an event but not on the DSA national page, we could be updating their contact info with stale information.
* Member info without an email address cannot be imported
* The data model for our members in Action Network is insufficiently descriptive in a lot of ways and makes tasks such as tracking attendance a pain
* The member info database only comes in handy for sending e-mails through action network. For other tasks that require distributing member info (e.g. phone banking) Action Network is inadequate

A custom CRM would give us the ability to track a lot more information about membership or prospective members, which could greatly benefit our organizing work. With more information about who is attending meetings, who has been contacted by mobilizers, who has paid dues, etc. we could do much more targeted organizing work and have a better way of measuring our success.

# Scope

For a V1 of a membership CRM, we'd want to implement a couple of things that will allow us to build more advanced types of functionality later on.

## Versioned Contact Info

We'd need all the basic info we keep about members, but versioned to avoid errors during manual entry / import (and with soft delete). Additionally, we should track member preferences about contact methods (text, email, phone, etc.) so that we can contact our membership using the channel they'll be most responsive on and would most prefer.

## Info about meeting attendance

A very basic attendance record for general meetings and subcommittee meetings would give us a lot of info about who our active members are, and allow us to implement strategies for engaging our "paper" membership for effectively.

## Info about membership status and dues 

We currently don't disambiguate between: people who have signed up to receive our e-mails, people who have lapsed on their dues (local or national) and people who are current on their dues. Being able to disambiguate these kinds of members/prospective members would allow us to do targeted email campaigns (e.g. an email request to pay your dues for those whose membership is about to expire).

## Import

CSV import would be necessary, and would improve upon Action Network's import by allowing us to import members without an e-mail address and by creating new versions of a user's contact info rather than overwrite it. Eventually we can do some sort of smart merging (for example, checking previous versions of contact info to see if the present info is more recent), but for an initial version just creating a new version of their info would be sufficient.

## Export to Action Network

Since our email list relies on up to date info in Action Network, functionality to upload the most recent version of each member's contact info would be necessary.

## Roles model

To meet the phone banking/mobilizer use case we'd need a very simple roles model that could look something like the following.

### Admin

Admins can
* Add, delete members and update their contact info
* See a member's attendance history / mark their attendance at an event
* See a member's dues history / mark a dues payment
* Create mobilizer users and assign members to them
* Export members to Action Network

### Mobilizer 

Mobilizers can
* See only the basic contact info for the members they were assigned (name, address, phone number, email)

## Security and privacy

The level of information we track about our membership is something we will likely have to negotiate between privacy (and liability) concerns and how valuable the information is in an organizing sense. In a perfect world, we could have totally anonymous members who never risk exposing their identities, but organizing work often requires some amount of trust to achieve wins. Still, we shouldn't be cavalier with any of this.

A project like this should:
* Make use of all proper cryptographic tools. Use socket-level encryption via TLS for all interaction w/ the application, use a proper KDF w/ a salt for login and constant time string comparison, etc.
* Probably be limited to use only when necessary. If it's practical to do so, it should be spun down when not being used by mobilizers or admins.
* Limit exposure of information to necessary parties. Only admins should be allowed to see all of a member's history, and mobilizers should be only be granted access to what they need.

# Future Ideas

In the future we might do things like:
* Implement a login-less attendance recording system to unify work w/ the intake form
* Allow mobilizers to record face-to-face meetings, phone banking call records, notes about members, etc.
* Implement advanced queries for export to an action network list to create targeted campaigns (e.g. sending members who have missed the last N meetings a targeted email, tracking interest in certain topics and alerting members based on those interests to upcoming events, etc.)

**Comment by jeremylow** [comment]
In terms of the Future Idea "Implement a login-less attendance recording system to unify work w/ the intake form": check out the work I did on https://github.com/jeremylow/dsa-sign-in-sheets/ which could be integrated into the CRM.
